name = "Fixxit Pros"
license = "Proprietary"
licenselink = "https://fixxitpros.com"
description = "Fixxit Pros home services theme"
homepage = "https://fixxitpros.com"
min_version = "0.92.0"

[author]
  name = "Fixxit Pros"
  homepage = "https://fixxitpros.com"
